global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "denoising_app_metrics"
    metrics_path: /metrics
    scrape_interval: 2s
    static_configs:
      - targets: ["denoising_app:8000"]
  
  - job_name: 'node_exporter'
    scrape_interval: 2s
    static_configs:
      - targets: ['node_exporter:9100'] 